name: Deploy to Test Environment

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log Start of Deployment
        run: echo "Test deployment started...."

      - name: Simulate Deployment Delay
        run: sleep 15

      - name: Log End of Deployment
        run: echo "Deployment completed."

      - name: Trigger Regression Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ItsMeYash777/cypress-Automation/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
