name: Deploy to Test Environment

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log Start of Deployment
        run: echo "Test deployment started..."

      - name: Simulate Deployment Delay
        run: sleep 15

      - name: Log End of Deployment
        run: echo "Deployment completed."

      - name: Trigger Regression Workflow
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} 
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'ItsMeYash777',
              repo: 'automation-repo',  
              workflow_id: 'deploy.yml', 
              ref: 'main',  
            });
            console.log('Triggered regression workflow:', response);
